import tkinter as tk
import billing as billing

global_l=[]
p=0

# functions here
def bill():
    global global_l
    global p
    global_l=[]
    p=0
    billitem()
    # print("after calling billitem ",global_l)
    # for i in global_l:
     #   print(i)
     #   p+=i[1]*i[2]
    # print("bill generated amount = ",p)


    


# generated by ai tool
def billitem_ai():
    def clear_name():
        name_entry.delete(0, tk.END)

    def clear_price():
        price_entry.delete(0, tk.END)

    def clear_quantity():
        quantity_entry.delete(0, tk.END)

    def submit():
        name = name_entry.get()
        price = price_entry.get()
        quantity = quantity_entry.get()
        
        try:
            price = float(price)
            quantity = int(quantity)
            global_l.append((name, price, quantity))
            clear_name()
            clear_price()
            clear_quantity()
            print("Item added to bill:", name, price, quantity)
        except ValueError:
            print("Invalid input for price or quantity")

    child_window = tk.Toplevel(root)
    child_window.title("Billing Module")

    # Labels and entry fields for billing data
    name_label = tk.Label(child_window, text="Product Name:")
    name_entry = tk.Entry(child_window)
    price_label = tk.Label(child_window, text="Price:")
    price_entry = tk.Entry(child_window)
    quantity_label = tk.Label(child_window, text="Quantity:")
    quantity_entry = tk.Entry(child_window)
    submit_button = tk.Button(child_window, text="Submit", command=submit)

    # Grid layout for labels and entry fields
    name_label.grid(row=0, column=0)
    name_entry.grid(row=0, column=1)
    price_label.grid(row=1, column=0)
    price_entry.grid(row=1, column=1)
    quantity_label.grid(row=2, column=0)
    quantity_entry.grid(row=2, column=1)
    submit_button.grid(row=3, columnspan=2)








    
    
# originally written by me    
def billitem():
    
    print("in the bill menu module")
    
    def clear_name():
        name_entry.delete(0,tk.END)
    def clear_phone():
        phone_entry.delete(0,tk.END)
    def clear1():
        product_name_entry.delete(0,tk.END)
    def clear2():
        price_entry.delete(0,tk.END)
    def clear3():
        quantity_entry.delete(0,tk.END)
    def clear_all():
        clear1()
        clear2()
        clear3()
    def submit():
        print("submit")
        
    def save():
        global global_l
        global p
        p=0
        for i in global_l:
            p+=i[1]*i[2]
        print("total bill = ",p)
        file_name=name_entry.get()
        file_name+=".txt"
        
        with open(file_name,"w") as file :
            file.write("\t\t\tname : ")
            file.write(name_entry.get())
            
        print("bill saved as word document")
        
    def next_item():
        global global_l
        name = product_name_entry.get()
        
        try :
            price = float(price_entry.get())
        except ValueError :
            bill.config(text="enter a valid value for price")
        #this entry should be a float
        try :
            quantity = int(quantity_entry.get())
        except ValueError :
            bill.config(text="enter a valid value for quantity")
        
        
        
        l=[]
        l.append(name)
        l.append(price)
        l.append(quantity)
        # print(l)
     
        global_l.append(l)
        print("appending ",l[0]," complete"," list ",global_l)
        clear_all()
        

    print("you are inside billing module")
    bill_items_details=[]

    child_window = tk.Toplevel(root)
    child_window.title("billing module")
    child_window.geometry("300x1000")

    #label creation

    customer_name = tk.Label(child_window, text="name")
    phone_number = tk.Label(child_window, text="phone")
    Billing = tk.Label(child_window,text="Billing")
    product_name =tk.Label(child_window,text="Product")
    price = tk.Label(child_window,text="Price")
    quantity = tk.Label(child_window,text="Quantity")
    bill = tk.Label(child_window,text="warnings")
    
    

    #entry field

    name_entry = tk.Entry(child_window)
    phone_entry = tk.Entry(child_window)
    product_name_entry = tk.Entry(child_window)
    price_entry = tk.Entry(child_window)
    quantity_entry = tk.Entry(child_window)
    

    #buttons field
    clear_name_button = tk.Button(child_window,text="Clear",command=clear_name)
    clear_phone_button = tk.Button(child_window,text="Clear",command=clear_phone)
    clear1_button = tk.Button(child_window,text="Clear",command=clear1)
    clear2_button = tk.Button(child_window,text="Clear",command=clear2)
    clear3_button = tk.Button(child_window,text="Clear",command=clear3)
    clear_all_button = tk.Button(child_window,text="Clear",command=clear_all)
   # submit_button = tk.Button(root,text="Submit",command=submit)
    save_button = tk.Button(child_window,text="Save",command=save)
    next_button = tk.Button(child_window,text="next",command=next_item)
    
    
    
    #grid layout

    customer_name.grid(row=0,column=0)
    name_entry.grid(row=0,column=1)
    clear_name_button.grid(row=0,column=2)
    
    phone_number.grid(row=1,column=0)
    phone_entry.grid(row=1,column=1)
    clear_phone_button.grid(row=1,column=2)
    Billing.grid(row=2,column=0,columnspan=2)
    
    product_name.grid(row=3 ,column=0 )
    product_name_entry.grid(row=3 ,column=1 ,padx=10)
    clear1_button.grid(row=3 ,column=2)
    
    price.grid(row=4 ,column=0 )
    price_entry.grid(row=4 ,column=1 )
    clear2_button.grid(row=4 ,column=2)
    
    quantity.grid(row=5 ,column=0 )
    quantity_entry.grid(row=5 ,column=1 )
    clear3_button.grid(row=5 ,column=2)
    
    clear_all_button.grid(row=6 ,column=0)
  #  submit_button.grid(row=6 ,column=1)
    next_button.grid(row=6 ,column=2)
    
    save_button.grid(row=7 ,column=0,columnspan=3)
    bill.grid(row=8 ,column=0 ,columnspan=3)

    # return global_l


    
    
def add_stock():
    print("over")
def report():
    print("over")
def exit1():
    print("thank you")
    exit()

print("you are inside main module")
#create main window
root=tk.Tk()
root.geometry("500x500")
root.title("inventory")

#creating labels
main_title = tk.Label(root,text="Inventory management ")
name = tk.Label(root,text="Name ")
password = tk.Label(root, text="Password")

#creating input entry fields
name_entry = tk.Entry(root)
password_entry = tk.Entry(root)

#creating buttons
billing_button = tk.Button(root,text="Billing",command=bill)
add_stock_button = tk.Button(root,text="add stock",command=add_stock)
report_button = tk.Button(root,text="Report", command=report)
exit_button = tk.Button(root,text="exit",command=exit1)

#arranging buttons and labels in grid system
main_title.grid(row = 0, column=0 , columnspan=2)
name.grid(row=1,column=0)
name_entry.grid(row=1,column=1)
password.grid(row=2,column=0)
password_entry.grid(row=2,column=1)
billing_button.grid(row=3 ,column=0,columnspan=2)
add_stock_button.grid(row=4 ,column=0,columnspan=2)
report_button.grid(row=5 ,column=0,columnspan=2)
exit_button.grid(row=6 ,column=0,columnspan=2)

root.mainloop()

